name: Build Docker Image on PR

# Trigger the workflow when a pull request is opened or updated targeting the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/startup_model:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/startup_model:latest